config/routes.rb
Rails.application.routes.draw do
  
  namespace :serve do
    resources :campaigns
    get 'settings/index'
  end

  namespace :ops do
    resources :ads do
      member do
        put :approve
      end
    end
    resources :creatives do
      member do
        put :approve
      end
    end
  end

  get 'reddit_proxy/subreddits'

  namespace :admin do
    resources :orgs do
      resources :memberships
    end
  end

  namespace :account do
    resources :users
  end

  namespace :superuser do
    resources :users
  end

  resources :orgs do
    resources :ads
    resources :creatives
    resources :campaigns do
      member do
        get :performance
      end
      resources :ads_campaigns
    end
    resources :assets
  end
  resources :users

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/destroy'
  

  root 'welcome#index'

end

app/controllers/ads_campaigns_controller.rb
class AdsCampaignsController < ApplicationController
  before_action :set_org
  before_filter :enforce_org_administrator
  before_action :set_campaign
  before_action :set_ad, only: [:destroy]
  
  def new
    @ads_campaigns = @campaign
  end
  

  # POST /ads_campaigns
  # POST /ads_campaigns.json
  def create
    @ad = @org.ads.find(params[:ads_campaigns][:ad_id])
    @campaign.ads << @ad

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to [@campaign.org, @campaign], notice: 'Ad was successfully added to campaign.' }
        format.json { render :show, status: :created, location: [@campaign.org, @campaign] }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads_campaigns/1
  # DELETE /ads_campaigns/1.json
  def destroy
    @campaign.ads.delete(@ad)
    respond_to do |format|
      format.html { redirect_to [@campaign.org, @campaign], notice: 'Ad was successfully removed from campaign.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_org
    @org = Org.find_by_permalink(params[:org_id])
    raise ActiveRecord::RecordNotFound unless @org
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_campaign
    @campaign = @org.campaigns.find(params[:campaign_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_ad
    @ad = @org.ads.find(params[:id])
  end
end

app/helpers/ads_campaigns_helper.rb
module AdsCampaignsHelper
end

app/views/ads_campaigns/_form.html.erb
<%= form_tag(org_campaign_ads_campaigns_path(@org, @campaign), method: :post) do %>
<% if @ads_campaigns.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
  <strong><%= pluralize(@ads_campaigns.errors.count, "error") %> prohibited this ad from being added:</strong>

  <ul>
    <% @ads_campaigns.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="form-group<%= @ads_campaigns.errors[:ad_id].empty? ? "" : " has-error has-feedback" %>">
    <%= label_tag 'ads_campaigns[ad_id]', 'Ad', { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= select_tag 'ads_campaigns[ad_id]', options_for_select(@org.ads.map {|a| [ a.title, a.id ] }), { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="actions text-center">
  <%= submit_tag 'Run', class: "btn btn-success" %>
</div>
<% end %>

app/views/ads_campaigns/new.html.erb
<% content_for :page_title do %>
Add an Ad to Your Campaign - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      Run Ad
      <small><%= @org.name %></small>
    </h1>
  </div>

  <%= render 'form' %>

  <div class="clearfix"></div>
  <%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, org_campaigns_path(@org), class: "btn btn-default" %>
</div>