config/routes.rb
Rails.application.routes.draw do
  
  namespace :serve do
    resources :campaigns
    get 'settings/index'
  end

  namespace :ops do
    resources :ads do
      member do
        put :approve
      end
    end
    resources :creatives do
      member do
        put :approve
      end
    end
  end

  get 'reddit_proxy/subreddits'

  namespace :admin do
    resources :orgs do
      resources :memberships
    end
  end

  namespace :account do
    resources :users
  end

  namespace :superuser do
    resources :users
  end

  resources :orgs do
    resources :ads
    resources :creatives
    resources :campaigns do
      member do
        get :performance
      end
      resources :ads_campaigns
    end
    resources :assets
  end
  resources :users

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/destroy'
  

  root 'welcome#index'

end

app/models/org.rb
class Org < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :memberships, dependent: :destroy
  has_many :assets, dependent: :destroy
  has_many :creatives, dependent: :destroy
  has_many :ads, dependent: :destroy
  has_many :campaigns, dependent: :destroy
  
  before_validation :autofill_permalink_if_blank
  
  validates :permalink, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9\-_]+\Z/ }
  
  def autofill_permalink_if_blank
    return true unless self.permalink.blank? # Bypass if permalink is already set
    self.permalink = AutoPermalink::cleaned_deduped_permalink(self.class, self.name)
  end

  def to_param
    self.permalink
  end
end

app/controllers/admin/orgs_controller.rb
class Admin::OrgsController < ApplicationController
  before_action :set_org
  before_filter :enforce_auth
  before_filter :enforce_org_administrator

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/1/edit
  def edit
  end

  # PATCH/PUT /orgs/1
  # PATCH/PUT /orgs/1.json
  def update
    respond_to do |format|
      if @org.update(org_params)
        format.html { redirect_to [:admin, @org], notice: 'Org was successfully updated.' }
        format.json { render :show, status: :ok, location: [:admin, @org] }
      else
        format.html { render :edit }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.json
  def destroy
    @org.destroy
    respond_to do |format|
      format.html { redirect_to orgs_url, notice: 'Org was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_org
    @org = Org.find_by_permalink(params[:id])
    raise ActiveRecord::RecordNotFound unless @org
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:name, :permalink, :email, :phone, :url, :street_address1, :street_address2, :city, :state_province_region, :zip_postal_code, :country_code, :timezone, :currency_code)
    end
end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
  before_action :set_org, only: [:show]
  before_filter :enforce_auth, only: [:new, :create]

  # GET /orgs
  # GET /orgs.json
  def index
    @orgs = Org.all
  end

  # GET /orgs/1
  # GET /orgs/1.json
  def show
  end

  # GET /orgs/new
  def new
    @org = authed_user.orgs.build
  end

  # POST /orgs
  # POST /orgs.json
  def create
    @org = authed_user.orgs.build(org_params)

    respond_to do |format|
      if @org.save
        format.html { redirect_to @org, notice: 'Org was successfully created.' }
        format.json { render :show, status: :created, location: @org }
      else
        format.html { render :new }
        format.json { render json: @org.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_org
    @org = Org.find_by_permalink(params[:id])
    raise ActiveRecord::RecordNotFound unless @org
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def org_params
      params.require(:org).permit(:name, :permalink, :email, :phone, :url, :street_address1, :street_address2, :city, :state_province_region, :zip_postal_code, :country_code, :timezone, :currency_code)
    end
end

app/helpers/admin/orgs_helper.rb
module Admin::OrgsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/views/admin/orgs/_form.html.erb
<%= form_for([:admin, @org]) do |f| %>
<% if @org.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
  <strong><%= pluralize(@org.errors.count, "error") %> prohibited this org from being saved:</strong>

  <ul>
    <% @org.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="form-group<%= f.object.errors[:name].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :name, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :name, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:permalink].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :permalink, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :permalink, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:email].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :email, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :email, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:phone].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :phone, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :phone, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:url].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :url, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :url, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:owner_id].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :owner_id, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :owner_id, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:street_address1].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :street_address1, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :street_address1, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:street_address2].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :street_address2, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :street_address2, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:city].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :city, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :city, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:state_province_region].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :state_province_region, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :state_province_region, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:zip_postal_code].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :zip_postal_code, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :zip_postal_code, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:country_code].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :country_code, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :country_code, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:timezone].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :timezone, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.select :timezone, ActiveSupport::TimeZone::MAPPING.keys.map{|key| [ActiveSupport::TimeZone::MAPPING[key], key] }, {}, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:currency_code].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :currency_code, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :currency_code, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="actions text-center">
  <%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/admin/orgs/edit.html.erb
<% content_for :page_title do %>
Edit Org - 
<% end %>
<div class="container">
<div class="page-header">
<h1>Editing Org</h1>
</div>

<%= render 'form' %>

<div class="clearfix"></div>
<div class="pull-left">
<%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, @org, class: "btn btn-default" %>
</div>
<div class="pull-right">
<%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete org...".html_safe, @org, method: :delete, data: { confirm: "Are you sure you want to delete this org?" }, class: "btn btn-danger" %>
</div>
</div>

app/views/admin/orgs/show.html.erb
<% content_for :page_title do %>
Org Details - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      <div class="pull-left">
        <%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, orgs_path, class: "btn btn-default", title: "Back to orgs" %>
        &nbsp;
      </div>
      <% if authed_administrator %>
      <div class="pull-right">
        <%= link_to "<span class=\"glyphicon glyphicon-user\" aria-hidden=\"true\"></span> Members".html_safe, admin_org_memberships_path(@org), class: "btn btn-default" %>
        <%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_admin_org_path(@org), class: "btn btn-warning" %>
      </div>
      <% end %>
      Org Details
      <small><%= @org.name %></small>
    </h1>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Name</label>
    <div class="col-sm-9"><%= @org.name %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Permalink</label>
    <div class="col-sm-9"><%= @org.permalink %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Email</label>
    <div class="col-sm-9"><%= @org.email %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Phone</label>
    <div class="col-sm-9"><%= @org.phone %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Url</label>
    <div class="col-sm-9"><%= @org.url %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Owner</label>
    <div class="col-sm-9"><%= @org.owner %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Street address1</label>
    <div class="col-sm-9"><%= @org.street_address1 %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Street address2</label>
    <div class="col-sm-9"><%= @org.street_address2 %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">City</label>
    <div class="col-sm-9"><%= @org.city %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">State province region</label>
    <div class="col-sm-9"><%= @org.state_province_region %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Zip postal code</label>
    <div class="col-sm-9"><%= @org.zip_postal_code %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Country code</label>
    <div class="col-sm-9"><%= @org.country_code %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Timezone</label>
    <div class="col-sm-9"><%= @org.timezone %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Currency code</label>
    <div class="col-sm-9"><%= @org.currency_code %></div>
  </div>


  <hr/>
  
  <h3>
  <% if @org.assets.count == 0 %>
  Step 1: <%= link_to 'Add Assets', org_assets_path(@org) %> to be used in your ads, by uploading them!
  <% elsif @org.creatives.count == 0 %>
  Step 2: <%= link_to 'Build Creative', org_creatives_path(@org) %> to be used in your ads, by writing them!
  <% elsif @org.ads.count == 0 %>
  Step 3: <%= link_to 'Setup Ads', org_ads_path(@org) %> to tie creatives to targeting!
  <% elsif @org.campaigns.count == 0 %>
  Step 4: <%= link_to 'Run a campaign', org_campaigns_path(@org) %> for your ads!
  <% else %>
  Looks like you're doing great :) <%= link_to 'Check on your campaigns', org_campaigns_path(@org) %>.
  <% end %>
  </h3>

  <hr/>
  
  <div class="row">
    <label class="col-sm-3 text-right text-muted">Campaigns</label>
    <div class="col-sm-9"><%= link_to @org.campaigns.count, org_campaigns_path(@org) %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Ads</label>
    <div class="col-sm-9"><%= link_to @org.ads.count, org_ads_path(@org) %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Creatives</label>
    <div class="col-sm-9"><%= link_to @org.creatives.count, org_creatives_path(@org) %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Asset Library</label>
    <div class="col-sm-9"><%= link_to @org.assets.count, org_assets_path(@org) %></div>
  </div>
</div>