config/routes.rb
Rails.application.routes.draw do
  
  namespace :serve do
    resources :campaigns
    get 'settings/index'
  end

  namespace :ops do
    resources :ads do
      member do
        put :approve
      end
    end
    resources :creatives do
      member do
        put :approve
      end
    end
  end

  get 'reddit_proxy/subreddits'

  namespace :admin do
    resources :orgs do
      resources :memberships
    end
  end

  namespace :account do
    resources :users
  end

  namespace :superuser do
    resources :users
  end

  resources :orgs do
    resources :ads
    resources :creatives
    resources :campaigns do
      member do
        get :performance
      end
      resources :ads_campaigns
    end
    resources :assets
  end
  resources :users

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/destroy'
  

  root 'welcome#index'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :org

  has_attached_file :file, storage: :s3, s3_credentials: { bucket: "#{ENV["PAPERCLIP_S3_BUCKET_PREFIX"]}-#{Rails.env}" }

  validates :org, presence: true
  validates :name, presence: true
  validates_attachment :file, presence: true, content_type: { content_type: /\Aimage\/.*\Z/ }, size: { in: 0..10.megabytes }
  
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_org
  before_filter :enforce_org_administrator
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = @org.assets
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = @org.assets.build
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = @org.assets.build(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to [@asset.org, @asset], notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: [@asset.org, @asset] }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to [@asset.org, @asset], notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: [@asset.org, @asset] }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to org_assets_url(@asset.org), notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find_by_permalink(params[:org_id])
      raise ActiveRecord::RecordNotFound unless @org
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = @org.assets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:file, :name, :html, :width, :height)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for([@asset.org, @asset]) do |f| %>
<% if @asset.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
  <strong><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</strong>

  <ul>
    <% @asset.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<div class="row">
  <div class="form-group<%= f.object.errors[:file].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :file, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.file_field :file, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:name].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :name, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :name, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:html].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :html, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_area :html, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:width].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :width, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.number_field :width, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:height].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :height, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.number_field :height, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="actions text-center">
  <%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/assets/edit.html.erb
<% content_for :page_title do %>
Edit Asset - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>Editing Asset</h1>
  </div>

  <%= render 'form' %>

  <div class="clearfix"></div>
  <div class="pull-left">
    <%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, [@asset.org, @asset], class: "btn btn-default" %>
  </div>
  <div class="pull-right">
    <%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete asset...".html_safe, [@asset.org, @asset], method: :delete, data: { confirm: "Are you sure you want to delete this asset?" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/assets/index.html.erb
<% content_for :page_title do %>
Assets - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      <div class="pull-left">
        <%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, admin_org_path(@org), class: "btn btn-default", title: "Back" %>
        &nbsp;
      </div>

      <div class="pull-right">
        <%= link_to "<span class=\"glyphicon glyphicon-plus-sign\" aria-hidden=\"true\"></span> New Asset".html_safe, [:new, @org, :asset], class: "btn btn-success" %>
      </div>
      Listing Assets
      <small><%= @org.name %></small>
    </h1>
  </div>

  <table class="table table-striped table-hover tablesorter" id="Assets-table">


    <thead>
      <tr>

        <th><span>Name</span></th>
        <th><span>File</span></th>
        <th><span>Html</span></th>
        <th><span>Width</span></th>
        <th><span>Height</span></th>
      
      </tr>
    </thead>

    <tbody>
      <% unless @assets.any? %>
      <tr id="empty-table">
        <td class="bg-warning" colspan="5">No assets created yet.</td>
      </tr>
      <% end %>
      <% @assets.each do |asset| %>
      <tr class="linked-row" data-href="<%= org_asset_path(asset.org, asset) %>">
    
        <td><%= link_to asset.name, [asset.org, asset] %></td>
        <td><%= link_to asset.file, [asset.org, asset] %></td>
        <td><%= link_to asset.html, [asset.org, asset] %></td>
        <td><%= link_to asset.width, [asset.org, asset] %></td>
        <td><%= link_to asset.height, [asset.org, asset] %></td>
        
        
        
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/assets/new.html.erb
<% content_for :page_title do %>
Create Asset - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      New Asset
      <small><%= @org.name %></small>
    </h1>
  </div>

  <%= render 'form' %>

  <div class="clearfix"></div>
  <%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, [@asset.org, :assets], class: "btn btn-default" %>
</div>

app/views/assets/show.html.erb
<% content_for :page_title do %>
asset Details - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      <div class="pull-left">
        <%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, org_assets_path(@asset.org), class: "btn btn-default", title: "Back to assets" %>
        &nbsp;
      </div>
      <div class="pull-right">
        <%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_org_asset_path(@asset.org, @asset), class: "btn btn-warning" %>
      </div>
      Asset Details
      <small><%= @org.name %></small>
    </h1>
  </div>
  
  <div class="row">
    <label class="col-sm-3 text-right text-muted">Name</label>
    <div class="col-sm-9"><%= @asset.name %></div>
  </div>
  
  <div class="row">
    <label class="col-sm-3 text-right text-muted">File</label>
    <div class="col-sm-9"><%= link_to @asset.file, @asset.file.url %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Html</label>
    <div class="col-sm-9"><%= @asset.html %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Width</label>
    <div class="col-sm-9"><%= @asset.width %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Height</label>
    <div class="col-sm-9"><%= @asset.height %></div>
  </div>

</div>