config/routes.rb
Rails.application.routes.draw do
  
  namespace :serve do
    resources :campaigns
    get 'settings/index'
  end

  namespace :ops do
    resources :ads do
      member do
        put :approve
      end
    end
    resources :creatives do
      member do
        put :approve
      end
    end
  end

  get 'reddit_proxy/subreddits'

  namespace :admin do
    resources :orgs do
      resources :memberships
    end
  end

  namespace :account do
    resources :users
  end

  namespace :superuser do
    resources :users
  end

  resources :orgs do
    resources :ads
    resources :creatives
    resources :campaigns do
      member do
        get :performance
      end
      resources :ads_campaigns
    end
    resources :assets
  end
  resources :users

  get '/auth/:provider/callback', to: 'sessions#create'
  get 'sessions/new'
  get 'sessions/destroy'
  

  root 'welcome#index'

end

app/models/creative.rb
class Creative < ActiveRecord::Base
  VALID_LOCALES = ['af', 'ar', 'az', 'bg', 'bn', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'de-AT', 'de-CH', 'el', 'en', 'en-AU', 'en-CA', 'en-GB', 'en-IE', 'en-IN', 'en-NZ', 'en-US', 'en-ZA', 'eo', 'es', 'es-419', 'es-AR', 'es-CL', 'es-CO', 'es-CR', 'es-EC', 'es-MX', 'es-PA', 'es-PE', 'es-US', 'es-VE', 'et', 'eu', 'fa', 'fi', 'fr', 'fr-CA', 'fr-CH', 'gl', 'he', 'hi', 'hi-IN', 'hr', 'hu', 'id', 'is', 'it', 'it-CH', 'ja', 'km', 'kn', 'ko', 'lo', 'lt', 'lv', 'mk', 'mn', 'ms', 'nb', 'ne', 'nl', 'nn', 'or', 'pl', 'pt', 'pt-BR', 'rm', 'ro', 'ru', 'sk', 'sl', 'sr', 'sv', 'sw', 'ta', 'th', 'tl', 'tr', 'tt', 'uk', 'ur', 'uz', 'vi', 'wo', 'zh-CN', 'zh-HK', 'zh-TW', 'zh-YUE']
  belongs_to :org
  belongs_to :asset
  
  validates :org, presence: true
  
  def update_as_approved_by(u)
    if !self.approved_at.blank?
      errors.add(:approved_at, " - has already been approved") 
      return false
    end
    self.update_attributes(approved_at: Time.now, approver_name: u.username)
  end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  before_action :set_org
  before_filter :enforce_org_administrator
  before_action :set_creative, only: [:show, :edit, :update, :destroy]

  # GET /creatives
  # GET /creatives.json
  def index
    @creatives = @org.creatives
  end

  # GET /creatives/1
  # GET /creatives/1.json
  def show
  end

  # GET /creatives/new
  def new
    @creative = @org.creatives.build(locale: 'en-US')
  end

  # GET /creatives/1/edit
  def edit
  end

  # POST /creatives
  # POST /creatives.json
  def create
    @creative = @org.creatives.build(creative_params)

    respond_to do |format|
      if @creative.save
        format.html { redirect_to [@creative.org, @creative], notice: 'Creative was successfully created.' }
        format.json { render :show, status: :created, location: [@creative.org, @creative] }
      else
        format.html { render :new }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatives/1
  # PATCH/PUT /creatives/1.json
  def update
    respond_to do |format|
      if @creative.update(creative_params)
        format.html { redirect_to [@creative.org, @creative], notice: 'Creative was successfully updated.' }
        format.json { render :show, status: :ok, location: [@creative.org, @creative] }
      else
        format.html { render :edit }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatives/1
  # DELETE /creatives/1.json
  def destroy
    @creative.destroy
    respond_to do |format|
      format.html { redirect_to org_creatives_url(@creative.org), notice: 'Creative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_org
      @org = Org.find_by_permalink(params[:org_id])
      raise ActiveRecord::RecordNotFound unless @org
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_creative
      @creative = @org.creatives.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def creative_params
      params.require(:creative).permit(:asset_id, :title, :url, :postername, :posterid, :promoted_thingid, :locale, :attachment_type, :attachment_html)
    end
end

app/controllers/ops/creatives_controller.rb
class Ops::CreativesController < ApplicationController
  before_filter :enforce_auth
  before_filter :enforce_superuser
  before_action :set_creative, only: [:approve]
  
  def index
    @creatives = Creative.all
  end

  # PATCH/PUT /ops/creatives/1/approve
  # PATCH/PUT /ops/creatives/1/approve.json
  def approve
    respond_to do |format|
      if @creative.update_as_approved_by(authed_user)
        format.html { redirect_to ops_creatives_path, notice: 'Creative was successfully approved.' }
        format.json { render :show, status: :ok, location: ops_creatives_path }
      else
        format.html { redirect_to edit_org_creative_path(@creative.org, @creative) }
        format.json { render json: @creative.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_creative
    @creative = Creative.find(params[:id])
  end
end

app/helpers/creatives_helper.rb
module CreativesHelper
end

app/helpers/ops/creatives_helper.rb
module Ops::CreativesHelper
end

app/views/creatives/_form.html.erb
<%= form_for([@creative.org,@creative]) do |f| %>
<% if @creative.errors.any? %>
<div id="error_explanation" class="alert alert-danger" role="alert">
  <strong><%= pluralize(@creative.errors.count, "error") %> prohibited this creative from being saved:</strong>

  <ul>
    <% @creative.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row">
  <div class="form-group<%= f.object.errors[:asset_id].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :asset_id, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.select :asset_id, @org.assets.order(name: :asc).map {|a| [ a.name, a.id ] }, { prompt: '-Select Uploaded Asset-' }, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:title].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :title, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :title, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:url].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :url, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :url, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:postername].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :postername, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :postername, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:posterid].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :posterid, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :posterid, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:promoted_thingid].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :promoted_thingid, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :promoted_thingid, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:locale].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :locale, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.select :locale, Creative::VALID_LOCALES.map {|a| [ a, a ] }, { prompt: '-Select Locale (Language)-' }, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:attachment_type].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :attachment_type, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_field :attachment_type, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group<%= f.object.errors[:attachment_html].empty? ? "" : " has-error has-feedback" %>">
    <%= f.label :attachment_html, { class: "control-label col-sm-2" } %>
    <div class="col-sm-10">
      <%= f.text_area :attachment_html, { class: "form-control" } %>
    </div>
  </div>
</div>
<div class="actions text-center">
  <%= f.submit class: "btn btn-success" %>
</div>
<% end %>

app/views/creatives/edit.html.erb
<% content_for :page_title do %>
Edit Creative - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>Editing Creative</h1>
  </div>

  <%= render 'form' %>

  <div class="clearfix"></div>
  <div class="pull-left">
    <%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, [@creative.org, @creative], class: "btn btn-default" %>
  </div>
  <div class="pull-right">
    <%= link_to "<span class=\"glyphicon glyphicon-trash\" aria-hidden=\"true\"></span> Delete creative...".html_safe, [@creative.org, @creative], method: :delete, data: { confirm: "Are you sure you want to delete this creative?" }, class: "btn btn-danger" %>
  </div>
</div>

app/views/creatives/index.html.erb
<% content_for :page_title do %>
Creatives - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      <div class="pull-left">
        <%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, admin_org_path(@org), class: "btn btn-default", title: "Back" %>
        &nbsp;
      </div>

      <div class="pull-right">
        <%= link_to "<span class=\"glyphicon glyphicon-plus-sign\" aria-hidden=\"true\"></span> New Creative".html_safe, [:new, @org, :creative], class: "btn btn-success" %>
      </div>
      Listing Creatives

      <small><%= @org.name %></small>
    </h1>
  </div>

  <table class="table table-striped table-hover tablesorter" id="Creatives-table">


    <thead>
      <tr>
  
        <th><span>Asset</span></th>
        <th><span>Title</span></th>
        <th><span>Url</span></th>
        <th><span>Postername</span></th>
        <th><span>Posterid</span></th>
        <th><span>Promoted thingid</span></th>
        <th><span>Locale</span></th>
        <th><span>Attachment type</span></th>
        <th><span>Attachment html</span></th>
        <th><span>Approved at</span></th>
        <th><span>Approver name</span></th>
    
      </tr>
    </thead>

    <tbody>
      <% unless @creatives.any? %>
      <tr id="empty-table">
        <td class="bg-warning" colspan="11">No creatives created yet.</td>
      </tr>
      <% end %>
      <% @creatives.each do |creative| %>
      <tr class="linked-row" data-href="<%= org_creative_path(creative.org, creative) %>">
    
        <td><%= link_to creative.asset.id, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.title, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.url, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.postername, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.posterid, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.promoted_thingid, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.locale, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.attachment_type, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.attachment_html, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.approved_at, org_creative_path(creative.org, creative) %></td>
        <td><%= link_to creative.approver_name, org_creative_path(creative.org, creative) %></td>
      
      
      
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/creatives/new.html.erb
<% content_for :page_title do %>
Create Creative - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      New Creative
      <small><%= @org.name %></small>
    </h1>
  </div>

  <%= render 'form' %>

  <div class="clearfix"></div>
  <%= link_to "<span class=\"glyphicon glyphicon-ban-circle\" aria-hidden=\"true\"></span> Cancel".html_safe, org_creatives_path(@org), class: "btn btn-default" %>
</div>

app/views/creatives/show.html.erb
<% content_for :page_title do %>
Creative Details - 
<% end %>
<div class="container">
  <div class="page-header">
    <h1>
      <div class="pull-left">
        <%= link_to "<span class=\"glyphicon glyphicon-step-backward\" aria-hidden=\"true\"></span>".html_safe, org_creatives_path(@creative.org), class: "btn btn-default", title: "Back to creatives" %>
        &nbsp;
      </div>
      <div class="pull-right">
        <%= link_to "<span class=\"glyphicon glyphicon-pencil\" aria-hidden=\"true\"></span> Edit".html_safe, edit_org_creative_path(@creative.org, @creative), class: "btn btn-warning" %>
      </div>
      Creative Details

      <small><%= @org.name %></small>
    </h1>
  </div>


  <div class="row">
    <label class="col-sm-3 text-right text-muted">Asset</label>
    <div class="col-sm-9"><%= link_to @creative.asset.name, [@creative.asset.org, @creative.asset] %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Title</label>
    <div class="col-sm-9"><%= @creative.title %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Url</label>
    <div class="col-sm-9"><%= @creative.url %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Postername</label>
    <div class="col-sm-9"><%= @creative.postername %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Posterid</label>
    <div class="col-sm-9"><%= @creative.posterid %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Promoted thingid</label>
    <div class="col-sm-9"><%= @creative.promoted_thingid %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Locale</label>
    <div class="col-sm-9"><%= @creative.locale %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Attachment type</label>
    <div class="col-sm-9"><%= @creative.attachment_type %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Attachment html</label>
    <div class="col-sm-9"><%= @creative.attachment_html %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Approved at</label>
    <div class="col-sm-9"><%= @creative.approved_at %></div>
  </div>

  <div class="row">
    <label class="col-sm-3 text-right text-muted">Approver name</label>
    <div class="col-sm-9"><%= @creative.approver_name %></div>
  </div>

</div>